import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// Components
import Footer from './components/Footer.tsx';

// Storyblok
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc';
import StoryblokBridgeLoader from '@storyblok/react/bridge-loader';

import Page from './components/storyblok/Page.tsx';
import Grid from './components/storyblok/Grid.tsx';
import Feature from './components/storyblok/Feature.tsx';
import Teaser from './components/storyblok/Teaser.tsx';

storyblokInit({
  accessToken: process.env.STORYBLOK_API_TOKEN,

  use: [apiPlugin],
  components: {
    feature: Feature,
    grid: Grid,
    page: Page,
    teaser: Teaser,
  },
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
      <StoryblokBridgeLoader options={{}} />
    </html>
  );
}
